# Use official OpenJDK image
FROM openjdk:17

# Set working directory
WORKDIR /app

# Copy Java file into container
COPY Main.java .

# Compile Java program
RUN javac Main.java

# Run the program
CMD ["java", "Main"]
